In [6]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://plotly.github.io/datasets/country_indicators.csv')

In [3]:
df.head()

,Country Name,Indicator Name,Year,Value
0,Arab World,"Agriculture, value added (% of GDP)",1962,NaN
1,Arab World,CO2 emissions (metric tons per capita),1962,0.760996
2,Arab World,Domestic credit provided by financial sector (...,1962,18.168690
3,Arab World,Electric power consumption (kWh per capita),1962,NaN
4,Arab World,Energy use (kg of oil equivalent per capita),1962,NaN

In [8]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_dash.csv")

In [10]:
df['Launch Site'].unique()

<ArrowStringArray>
['CCAFS LC-40', 'VAFB SLC-4E', 'KSC LC-39A', 'CCAFS SLC-40']
Length: 4, dtype: str

In [13]:
df.head()

,Unnamed: 0,Flight Number,Launch Site,class,Payload Mass (kg),Booster Version,Booster Version Category,result
0,0,1,CCAFS LC-40,0,0.0,F9 v1.0 B0003,v1.0,False
1,1,2,CCAFS LC-40,0,0.0,F9 v1.0 B0004,v1.0,False
2,2,3,CCAFS LC-40,0,525.0,F9 v1.0 B0005,v1.0,False
3,3,4,CCAFS LC-40,0,500.0,F9 v1.0 B0006,v1.0,False
4,4,5,CCAFS LC-40,0,677.0,F9 v1.0 B0007,v1.0,False

In [12]:
df['result'] = df['class'] == 1

In [18]:
df['class'].value_counts()

class
0    32
1    24
Name: count, dtype: int64

In [20]:
(
            
df['class']
            .map({0: 'Failure', 1: 'Success'})
            .value_counts()
            .reset_index()
        )

     class  count
0  Failure     32
1  Success     24